

trigger:
- master

stages:
- stage: Build
  jobs:

  - job: 'Build'
    pool: server
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        Phase: 'STARTED'
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'DevOps Connection'
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        Phase: 'COMPLETED'





