
trigger:
- master
name: $(BuildDefinitionName).$(BuildID)
variables:
  System.Debug: true

jobs:
- job: 'Build'
  steps:
  - task: ServiceNow-DevOps-Agent-Job-Notification@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      Phase: 'STARTED'
  - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      artifactsPayload: |
        {
                   "artifacts": [
                   {
                       "name": "globex-web.war",
                       "repositoryName": "corpsite-ADO",
                       "version": "1.0.$(Build.BuildId)",
                       "semanticVersion": "1.0.$(Build.BuildId)"
                   }]}
  - task: ServiceNow-DevOps-Agent-Job-Notification@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      Phase: 'COMPLETED'

- job: 'ChangeJob'
  pool: server
  steps:
  - task: ServiceNow-DevOps-Server-Job-Notification@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      UpstreamJob: 'Build'
      Phase: 'STARTED'

  - task: ServiceNow-DevOps-Server-Package-Registration@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      packageRegistrationPayload: |
        {
            "name": "CorpsitePackage",
            "artifacts": [
            {
                "name": "globex-web.war",
                "repositoryName": "corpsite-ADO",
                "version": "1.0.$(build.buildId)",
                "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                "taskExecutionNumber":"$(build.buildId)",
                "stageName":"$(system.jobDisplayName)",
                "branchName":"$(build.sourceBranchName)"
            }],
            "pipelineName":"$(system.teamProject)/$(build.definitionName)",
            "taskExecutionNumber":"$(build.buildId)",
            "stageName":"$(system.jobDisplayName)",
            "branchName":"$(build.sourceBranchName)"
        }
      artifactToolIdExists: false

  - task: ServiceNow-DevOps-Server-Change-Acceleration@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      UpstreamJob: 'Build'


  - task: ServiceNow-DevOps-Server-Job-Notification@1
    inputs:
      connectedServiceName: 'DevOps Connection'
      UpstreamJob: 'Build'
      Phase: 'COMPLETED'
    condition: true




