# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ServiceNow-DevOps-Server-Change-Acceleration@1
  inputs:
    connectedServiceName: 'DevOps Connection'
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'DevOps Connection'
    Phase: 'STARTED'




