

trigger:
- master

stages:
- stage: AgentChangeJob
  jobs:

  - job: 'AgentChangeJob'
    steps:

    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        Phase: 'STARTED'

    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        artifactsPayload: |
          {
            "artifacts": [
            {
                "name": "globex-web.war",
                "repositoryName": "corpsite-ADO",
                "version": "1.0.$(Build.BuildId)",
                "semanticVersion": "1.0.$(Build.BuildId)"
            }]
          }

    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        packageName: "CorpsitePackage"
        artifactsPayload: |
          {
            "name": "CorpsitePackage",
            "artifacts": [
            {
                "name": "globex-web.war",
                "repositoryName": "corpsite-ADO",
                "version": "1.0.$(Build.BuildId)",
                "pipelineName":"$(system.teamProject)/$(AgentChangeJob.definitionName)",
                "taskExecutionNumber":"$(Build.BuildId)",
                "stageName":"$(system.jobDisplayName)",
                "branchName":"$(AgentChangeJob.sourceBranchName)"
            }],
            "pipelineName":"$(system.teamProject)/$(build.definitionName)",
            "taskExecutionNumber":"$(Build.BuildId)",
            "stageName":"$(system.jobDisplayName)",
            "branchName":"$(AgentChangeJob.sourceBranchName)"
          }

- stage: ServerChangeJob
  jobs:
  - job: 'ServerChangeJob'
    pool: server
    steps:
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'DevOps Connection'

    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'DevOps Connection'
        Phase: 'COMPLETED'





